version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
#    command: gunicorn finvinci.wsgi:application --bind 0.0.0.0:8000
    command: python3 manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
  redis:
    image: "redis:alpine"
  celery:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: celery -A finvinci worker --loglevel=DEBUG
    env_file: .env
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db
      - redis
  celery-beat:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: celery -A finvinci beat --loglevel=DEBUG
    env_file: .env
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db
  nginx:
    build: ./nginx
    ports:
      - 81:80
    depends_on:
      - web
    volumes:
      - static_volume:/usr/src/app/staticfiles

volumes:
  postgres_data:
  static_volume:
